params:
  epochs: 100
  category: wood
  num_train_images: 1
  height: 256
  width: 256
  mean: 0
  std: 1
  num_basis: 10
  patch_size: 8
  tolerance: 1e-8

mlflow:
  tracking_uri: databricks
  experiment_name: /Users/inoue@nablas.com/SMAD_mvtec
  run_name: ${params.category}

transforms:
  train:
    - name: albumentations - Resize
      args:
        height: ${params.height}
        width: ${params.width}
        p: 1
    - name: albumentations - Normalize
      args:
        mean: ${params.mean}
        std: ${params.std}
        p: 1
  test:
    - name: albumentations - Resize
      args:
        height: ${params.height}
        width: ${params.width}
        p: 1
    - name: albumentations - Normalize
      args:
        mean: ${params.mean}
        std: ${params.std}
        p: 1

datasets:
  train:
    name: smad.datasets - MVTecDataset
    args:
      data_dir: /data
      query_list:
        - mode=='train' & category=='${params.category}'
  test:
    name: smad.datasets - MVTecDataset
    args:
      data_dir: /data
      query_list:
        - mode=='test' & category=='${params.category}'

dataloaders:
  train:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.num_train_images}
      num_workers: ${params.num_train_images}
      pin_memory: True
      shuffle: True
  test:
    name: torch.utils.data - DataLoader
    args:
      batch_size: 1
      num_workers: 1
      pin_memory: True
      shuffle: True
